# Random seed for full reproducibility
seed: 42

data:
  dataset: "mnist"
  params:
    data_dir: "examples/datasets/mnist"
    batch_size: 256
    val_split: 0.1
    shuffle_buffer: 10000
    seed: 42

model:
  model: "cnn"
  params:
    num_classes: 10
    input_shape: [28, 28, 1]
    conv_filters: [64, 32]
    dense_units: 128
    dropout_rate: 0.1

train:
  student_lr: 0.001
  teacher_lr: 0.0002
